### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by alexander-you** [Krajpurohit/QueueItemTracker#1] opened 2023-03-18 19:51 UTC
Hi, 

it seems that there is no RTL support And I was wondering if there is any planning to create or update for this kind of support.
specially relevant for Hebrew in Arabic languages.

![image](https://user-images.githubusercontent.com/39707813/226134284-75f11692-1153-4aff-8968-6274932ecba9.png)

![image](https://user-images.githubusercontent.com/39707813/226134321-6ebfd28a-e6c8-449e-8e87-45ad2b560d45.png)

![image](https://user-images.githubusercontent.com/39707813/226134328-ade912ac-f08a-4ba1-950e-7a2e95ab9307.png)

**Comment by Krajpurohit** [comment] 2023-04-04 07:24
Hi Alex,

Thanks for reaching out, issue is now fixed please try latest solution file form [here](https://github.com/Krajpurohit/QueueItemTracker/tree/master/solution).

![image](https://user-images.githubusercontent.com/37947679/229718527-d4a76b95-4bf9-4a6e-b0cf-aca8a1e97fdf.png)

**Comment by alexander-you** [comment] 2023-04-04 07:46
I don't know if I did something wrong, I reuploaded the solution and this is the result
![image](https://user-images.githubusercontent.com/39707813/229723688-226dbb0b-baae-44d6-93b3-ea688617d71c.png)

**Comment by Krajpurohit** [comment] 2023-04-04 08:41
Hi Alex,

Can you remove the existing PCF from your instance and try importing again.

**Comment by alexander-you** [comment] 2023-04-04 10:25
Hi
unfortunately it's the same 

![image](https://user-images.githubusercontent.com/39707813/229763785-bb73d0df-9a2c-48ee-a039-c6f799ceb557.png)

**Comment by Krajpurohit** [comment] 2023-04-04 10:39
I will try to reproduce this on my trial and fix it.

**Comment by Krajpurohit** [comment] 2023-04-05 05:23
Hi Alex,

Unfortunately i cannot reproduce this at my end.

Can you try below steps if not already done.

1. Remove control from case form.
2. Delete PCF from your environment.
3. Import solution again from [here](https://github.com/Krajpurohit/QueueItemTracker/tree/master/solution).

**Closed as completed by Krajpurohit** 2023-04-05 05:23 UTC
Labels: bug
